server.port=${env.SERVER_PORT:3000}
spring.application.name=nursery-backend

# MongoDB Configuration
spring.data.mongodb.uri=${env.MONGODB_URI:mongodb+srv://chahinchaaben_db_user:jEzOOUtah5mqoDEZ@nursery-cluster.w1n6yu6.mongodb.net/nursery_db?appName=nursery-cluster}
spring.data.mongodb.auto-index-creation=true
